apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-demo-app
  annotations:
    branch: test
    source-repository: test 
spec:
  replicas: 4
  template:
    metadata:
      labels:
        name: my-demo-app
        app: my-demo-app
    spec:
      containers:
      - name: my-demo-app
        image: test
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
