apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flaskapp
  annotations:
    branch: {{CF_BRANCH_TAG_NORMALIZED}}
    source-repository: {{CF_REPO_NAME}}  
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - name: mqbui1
        image: myrepo/mqbui1:{{CF_BRANCH}}-{{CF_REVISION}}
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
