apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: python-demo
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        revision: "{{CF_REVISION}}"
      labels:
        app: python-demo
    spec:
      containers:
        - name: python-demo
          image: myrepo/python-demo:{{CF_BRANCH}}-{{CF_REVISION}}
          ports:
            - containerPort: 80
              name: http
