apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: python-demo
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        revision: "{{CF_REVISION}}"
      labels:
        app: python-demo
    spec:
      containers:
        - name: python-demo
          image: mqbui1/pythonflasksampleapp:{{CF_BRANCH}}
          ports:
            - containerPort: 80
              name: http
